# Generated by Django 3.2.5 on 2021-07-28 17:42
from django.core.management import call_command
from django.db import migrations, models


def load_fixtures(apps, schema_editor):
    call_command('loaddata', 'mydemodata', 'authentication')

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.RunPython(load_fixtures, migrations.RunPython.noop)
    ]
